### ISSUE TITLE
Support inline sourcemaps

### ISSUE THREAD

**Issue by tjallingt** [paazmaya/shuji#10]
### Expected behaviour

`shuji bundle.js` produce the same output as `shuji bundle.js.map` if bundle has an inline sourcemap. If it doesn't have a sourcemap it should throw an error.

### Actual behaviour

`shuji bundle.js` will write `shuji - Reverse engineering JavaScript and CSS sources from sourcemaps` to the console and exit without erroring or generating files

### Versions and environment

 * Operating system:
 * Node.js: v10.6.0
 * npm: 6.1.0
 * shuji: 0.4.0

Thank you and have some :stew:.

**Comment by tjallingt** [comment]
Yea i can take a look at implementing this

**Comment by paazmaya** [comment]
I started to look at this in https://github.com/paazmaya/shuji/tree/10-inline-sourcemaps

**Comment by paazmaya** [comment]
Will be released in https://github.com/paazmaya/shuji/releases/tag/v0.6.0 later today
