### ISSUE TITLE
Create original directory structure

### ISSUE THREAD

**Issue by BirdyUK** [paazmaya/shuji#11]
Firstly, Great job, Very useful tool. I just have one question which would make this tool the best thing since beer!

Is it possible to have this create the original directory structure as oppose to creating all the files in the current working directory?

For example, Once i run:  shuji -v app.bundle.js.map 

i get an sample file app.js

and that sample file contains this:

import React from 'react';
import Select from 'components/form/Select';

...
...
...

// WEBPACK FOOTER //
// ./app/webpack/react/components/Form/Form.js

Would it be possible to restore these files to the correct directory based on parsing the webpack footer text or using the import from?

Look forward to answer, Thanks.

**Comment by paazmaya** [comment]
Ouh, there is a forgotten #4

**Comment by falconmick** [comment]
I hope we get this soon :) this project rocks!

**Comment by paazmaya** [comment]
Please try with `v0.8.0`
