### ISSUE TITLE
node error？

### ISSUE THREAD

**Issue by mienv567** [paazmaya/shuji#14]
(node:6749) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ReferenceError: WebAssembly is not defined
(node:6749) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by paazmaya** [comment]
`ReferenceError: WebAssembly is not defined` might refer that the issue is somewhere else than in `shuji`...
