### ISSUE TITLE
Can you restore the src/components/ folder?

### ISSUE THREAD

**Issue by mienv567** [paazmaya/shuji#15]
Can you restore the src/components/ folder?

The current command is Shuji -v app.52896ad8f3c5ea5bf029.js.map -o /mnt/ios/3.

There will be conflicts Warning: File /mnt/ios/3/index.vue already exists, skipping!

Want to achieve the following original catalogue

/src
components
router
views
App.vue
main.js

**Comment by jingsam** [comment]
A fork package `@jingsam/shuji` will restore source structure.

**Comment by mienv567** [comment]
> A fork package `@jingsam/shuji` will restore source structure.

Thank you, but there is still a little bug.



> Pull request would be welcome to add such a functionality, with proper unit tests
You can pull his branch down and revise it.
 @jingsam/shuji

**Comment by kiwina** [comment]
not sure what bug you refer to i happen to make the exact same changes as @jingsam/shuji and it works just fine. Mind you then sources come from webpack you will have a problem ie
`
"webpack:///./src
`

**Comment by mysticaltech** [comment]
Something that would be great folks is, especially when the Webpack links return 404s, is to fetch from npmjs.com directly... And the private ones, not available there, use the code minified code "beautified", that would be a best-effort thing, what do you think, would it be possible? It would be partial reconstruction.

**Comment by paazmaya** [comment]
Please try with `v0.8.0`
