### ISSUE TITLE
增加文件目录

### ISSUE THREAD

**Issue by zhangdaren** [paazmaya/shuji#24]
### Expected behaviour

大佬，这个工具挺好用的。能把目录也还原出来不？像浏览器的调试工具一样

What it should have accomplished.

### Actual behaviour

How to reproduce with minimal working example.

### Versions and environment

 * Operating system:
 * Node.js:
 * npm:
 * shuji:

Thank you and have some :stew:.

**Comment by paazmaya** [comment]
You can always re-open with English description..
