### ISSUE TITLE
Add How to use Instructions to readme

### ISSUE THREAD

**Issue by koolamusic** [paazmaya/shuji#37]
The README file isn't really verbose on how you can use shuji on the comman line, apart from the command line reference, it's pretty much a lot of guess work on the outside. 

- Should I reference the URL path directly?
- Do I need the file in a local directory?
- Absolute or relative path?
- How do I handle multiple 'js.map` files in the same directory

**Comment by rodrigograca31** [comment]
Yeah I think a simple example is missing on the README:

just this would be great:
`shuji main.ad2fc4c4.chunk.js.map -o folder`

@paazmaya I can send a PR if you want.
