### ISSUE TITLE
You must provide the URL of lib/mappings.wasm by calling

### ISSUE THREAD

**Issue by ZiziBobo** [paazmaya/shuji#90]
Heeello everyone, I bumped into this problem when using shuji

**Error info**
```
➜ shuji .\bundle.js.map -o bundle.js.map.test
shuji - Reverse engineering JavaScript and CSS sources from sourcemaps
[path]\npm\node_modules\shuji\node_modules\source-map\lib\read-wasm.js:8
      throw new Error("You must provide the URL of lib/mappings.wasm by calling " +
            ^

using SourceMapConsumer
    at readWasm ([path]\npm\node_modules\shuji\node_modules\source-map\lib\read-wasm.js:8:13)
    at wasm ([path]\npm\node_modules\shuji\node_modules\source-map\lib\wasm.js:25:16)
    at [path]\npm\node_modules\shuji\node_modules\source-map\lib\source-map-consumer.js:264:14
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async readSources ([path]\npm\node_modules\shuji\lib\read-sources.js:24:20)
    at async handleInput ([path]\npm\node_modules\shuji\index.js:28:18)
    at async [path]\npm\node_modules\shuji\bin\shuji.js:151:23
```

**Environment**
```
win10
Node.js v18.12.1
shuji@0.7.0
npm 9.1.3
```

hava any solutions?😭

**Comment by Jarvie789** [comment]
I also encountered this error exception.
```
macOS13.4
Node.js v19.8.1
shuji@0.7.0
npm 9.5.1
```

**Comment by davidwang1953** [comment]
@Jarvie789 @ZiziBobo 这是source map的问题，它通过fetch函数来判断当前环境是浏览器还是node，之前的版本中它只存在于浏览器，但是从node 18开始也引入了该函数，导致source map错误的判断了当前的运行环境为浏览器，解决方法是修改源码里对应的判断(或许修改依赖里source map的版本也行)，如修改为：
```
typeof fetch === "function"
->
typeof window !== `undefined`
```

**Comment by thirdender** [comment]
I ran into the same error. `npx shuji FILE.min.js.map` produced this error. However, cloning this repository and running `node bin/shuji.js FILE.min.js.map` worked.

Alternatively, the error may also be resolved by version 0.8.0-beta.0 of the https://github.com/mozilla/source-map library, which changes the WASM loading detection (see https://github.com/mozilla/source-map/blob/master/CHANGELOG.md#080-beta0)

**Comment by marukaz** [comment]
I ran into this issue too.
As pointed out by @thirdender, this issue seems to be resolved in 0.8.0-beta.0 of source-map.
Also, I found that @paazmaya tried it in https://github.com/paazmaya/shuji/commit/4eab5ade695af2decc91f8820ce811d99ddba542 but reverted it in https://github.com/paazmaya/shuji/commit/bb25b6528460bc0f4362e763cd5318f58483c384. Was there anything wrong?

**Comment by cordosvictor** [comment]
@marukaz I managed to get it functioning by deliberately adjusting the `source-map` version to `0.8.0-beta.0` in the `package.json` file and then re-running the `yarn install` command.

```json
"dependencies": {
  "shuji": "^0.7.0"
},
"resolutions": {
  "source-map": "0.8.0-beta.0"
}
```

**Comment by paazmaya** [comment]
I did try with `0.8.0-beta.0`, but it seemed to make no difference and perhaps there came up some other issue that I cannot even recall...

If someone can provide minimal test cases via PR, I am happy to include them along with the fixes..

**Comment by paazmaya** [comment]
The version `0.8.0` of `shuji` is now available and "works for me"....
